### ISSUE TITLE
istal dis on a discord sv

### ISSUE THREAD

**Issue by Nintendero65pro** [SHAAARK72/amogums-bot#1]
am hell mi name is ben im 8 yrs old im so fanatic of amogus i play it since i burned 2011 i think idk ahh how do i isyal dis on a discord sv=!=!=!?!?!?!? am idony know how to cod am i know html see <br> hello im ben 8 2011 </br> pro pro yes am ok how to say it ### **_**s**_**

**Comment by Nintendero65pro** [comment]
yur code is so pro tyvm for doin this

**Comment by SHAAARK72** [comment]
You have to download and install it in your server.
